# .goreleaser.yaml (v2)
version: 2

builds:
  - id: p0d
    binary: p0d
    main: ./cmd/p0d/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  github:
    owner: simonmittag
    name: p0d

universal_binaries:
  - id: p0d
    replace: true

checksum:
  name_template: 'checksums.txt'

brews:
  - name: p0d
    homepage: https://github.com/simonmittag/p0d
    repository:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com
