---
exec:
  mode: binary
  durationSeconds: 30
  spacingMillis: 100
  threads: 256
  connections: 256
  logsampling: 0.1
req:
  method: GET
  url: http://localhost:60083/mse6/get
  headers:
    - Accept-Encoding: "identity"
res:
  code: 200
