---
exec:
  durationSeconds: 30
  threads: 100
  connections: 100
req:
  method: POST
  url: http://localhost:60083/mse6/post
  headers:
    - Accept-Encoding: "*"
  body: '[
     {
       "_id": "6258803a11df084c64305568",
       "index": 0,
       "guid": "ce2b6484-7685-478c-a64f-14f21a9548c5",
       "isActive": false,
       "balance": "$3,366.74",
       "picture": "http://placehold.it/32x32",
       "age": 21,
       "eyeColor": "blue",
       "name": "Benjamin Patel",
       "gender": "male",
       "company": "UNI",
       "email": "benjaminpatel@uni.com",
       "phone": "+1 (945) 423-3922",
       "address": "107 Bayard Street, Gorst, Illinois, 1681",
       "about": "Pariatur consectetur ullamco ea qui incididunt minim irure ea commodo commodo reprehenderit. Tempor mollit excepteur aliquip ut esse non cillum Lorem ullamco officia ut laboris. Proident officia culpa laborum ullamco voluptate aliqua tempor sint do et. Tempor nostrud enim duis dolor reprehenderit proident duis laboris eu nostrud. Qui ea amet eiusmod ullamco dolor pariatur velit Lorem velit magna ut excepteur et velit.\r\n",
       "registered": "2020-10-13T08:48:31 -11:00",
       "latitude": 85.484209,
       "longitude": -75.969499,
       "tags": [
         "laboris",
         "anim",
         "veniam",
         "amet",
         "laborum",
         "deserunt",
         "labore"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Cotton Mccall"
         },
         {
           "id": 1,
           "name": "Ada Hopkins"
         },
         {
           "id": 2,
           "name": "Lula Franks"
         }
       ],
       "greeting": "Hello, Benjamin Patel! You have 4 unread messages.",
       "favoriteFruit": "banana"
     },
     {
       "_id": "6258803abc6c2f913d00aeab",
       "index": 1,
       "guid": "bdac6fa8-578b-4bec-ab07-980e4bba856d",
       "isActive": false,
       "balance": "$2,230.66",
       "picture": "http://placehold.it/32x32",
       "age": 29,
       "eyeColor": "brown",
       "name": "Arline Jordan",
       "gender": "female",
       "company": "SUREPLEX",
       "email": "arlinejordan@sureplex.com",
       "phone": "+1 (952) 408-3720",
       "address": "227 Horace Court, Innsbrook, Oklahoma, 1318",
       "about": "Fugiat dolor nostrud est anim voluptate enim ut magna ea. Duis ad Lorem enim do duis voluptate elit labore nulla laborum. Enim ea duis mollit exercitation. Id dolore exercitation exercitation anim consectetur et et nisi in quis proident qui cillum. Id mollit qui pariatur nulla ea pariatur tempor exercitation ullamco excepteur fugiat enim elit.\r\n",
       "registered": "2014-05-15T11:15:12 -10:00",
       "latitude": 46.307515,
       "longitude": -114.567367,
       "tags": [
         "irure",
         "laborum",
         "in",
         "id",
         "officia",
         "aliquip",
         "dolore"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Rebekah Stevenson"
         },
         {
           "id": 1,
           "name": "Ila Ayers"
         },
         {
           "id": 2,
           "name": "Cantrell Alford"
         }
       ],
       "greeting": "Hello, Arline Jordan! You have 2 unread messages.",
       "favoriteFruit": "strawberry"
     },
     {
       "_id": "6258803aef900151af097357",
       "index": 2,
       "guid": "e1e69443-df04-4d07-b457-f34a8f67d542",
       "isActive": false,
       "balance": "$1,073.51",
       "picture": "http://placehold.it/32x32",
       "age": 36,
       "eyeColor": "brown",
       "name": "Solis Mullins",
       "gender": "male",
       "company": "COMVERGES",
       "email": "solismullins@comverges.com",
       "phone": "+1 (977) 458-3417",
       "address": "855 Bogart Street, Belfair, Wyoming, 3177",
       "about": "Eiusmod mollit Lorem anim sit excepteur eiusmod do et quis consequat aliquip consectetur laborum. Nulla nostrud aliqua deserunt amet sunt nostrud culpa voluptate. Veniam reprehenderit amet elit nostrud laborum culpa pariatur.\r\n",
       "registered": "2021-08-31T04:31:51 -10:00",
       "latitude": -36.266677,
       "longitude": -42.246477,
       "tags": [
         "tempor",
         "esse",
         "cupidatat",
         "velit",
         "qui",
         "ex",
         "enim"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Summers Glenn"
         },
         {
           "id": 1,
           "name": "Sutton Mcleod"
         },
         {
           "id": 2,
           "name": "Hansen Newman"
         }
       ],
       "greeting": "Hello, Solis Mullins! You have 3 unread messages.",
       "favoriteFruit": "strawberry"
     },
     {
       "_id": "6258803a3b47cbe98d632706",
       "index": 3,
       "guid": "05023f40-1e47-49c9-8770-4aa06d58e0db",
       "isActive": false,
       "balance": "$2,454.46",
       "picture": "http://placehold.it/32x32",
       "age": 39,
       "eyeColor": "brown",
       "name": "Tanya Price",
       "gender": "female",
       "company": "PLUTORQUE",
       "email": "tanyaprice@plutorque.com",
       "phone": "+1 (933) 481-3867",
       "address": "806 Martense Street, Gibbsville, Connecticut, 8256",
       "about": "Anim occaecat elit consectetur voluptate reprehenderit excepteur amet ea culpa. Excepteur ex deserunt qui sit. Dolore amet eiusmod veniam et exercitation dolor ea. Est proident magna id ullamco commodo culpa do nisi ipsum aliquip. Laboris consectetur officia consequat commodo esse. Exercitation velit aute dolor aliquip do duis do amet.\r\n",
       "registered": "2016-04-23T07:00:36 -10:00",
       "latitude": -1.1927,
       "longitude": -63.317625,
       "tags": [
         "non",
         "quis",
         "est",
         "est",
         "velit",
         "duis",
         "consequat"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Nunez Blankenship"
         },
         {
           "id": 1,
           "name": "Dolores Livingston"
         },
         {
           "id": 2,
           "name": "Downs Dodson"
         }
       ],
       "greeting": "Hello, Tanya Price! You have 1 unread messages.",
       "favoriteFruit": "strawberry"
     },
     {
       "_id": "6258803a894ceebf92fb40f1",
       "index": 4,
       "guid": "fa9ff12b-ffd0-4f0b-a023-98a1c9048f3b",
       "isActive": false,
       "balance": "$3,228.01",
       "picture": "http://placehold.it/32x32",
       "age": 40,
       "eyeColor": "green",
       "name": "Larson Sykes",
       "gender": "male",
       "company": "NAXDIS",
       "email": "larsonsykes@naxdis.com",
       "phone": "+1 (930) 494-3786",
       "address": "430 Vanderveer Place, Yorklyn, New Mexico, 5682",
       "about": "Nostrud tempor irure et esse sunt et qui consectetur reprehenderit nulla magna veniam. Proident aliquip minim exercitation culpa id do tempor anim ad in consequat esse. Adipisicing exercitation in Lorem aliquip sint cupidatat aute minim labore eu ut. Ea amet tempor do Lorem id mollit culpa.\r\n",
       "registered": "2016-12-14T04:13:20 -11:00",
       "latitude": 45.235406,
       "longitude": -29.294704,
       "tags": [
         "non",
         "veniam",
         "veniam",
         "incididunt",
         "ut",
         "incididunt",
         "deserunt"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Susana Rose"
         },
         {
           "id": 1,
           "name": "Lang Barrera"
         },
         {
           "id": 2,
           "name": "Buckley Morrow"
         }
       ],
       "greeting": "Hello, Larson Sykes! You have 10 unread messages.",
       "favoriteFruit": "strawberry"
     },
     {
       "_id": "6258803aba8355146493e56f",
       "index": 5,
       "guid": "fa101f26-921d-45c7-a62f-ad25749a0537",
       "isActive": false,
       "balance": "$1,815.48",
       "picture": "http://placehold.it/32x32",
       "age": 20,
       "eyeColor": "green",
       "name": "Durham Pace",
       "gender": "male",
       "company": "ROCKABYE",
       "email": "durhampace@rockabye.com",
       "phone": "+1 (914) 585-3737",
       "address": "767 Dearborn Court, Faywood, Oregon, 9101",
       "about": "Ipsum consequat cupidatat ea id. Sint fugiat excepteur amet labore dolor nulla laboris incididunt irure culpa sunt sit voluptate. Culpa adipisicing nulla ullamco aute eiusmod sunt occaecat. Nisi est eiusmod enim incididunt minim adipisicing minim eu enim ad exercitation. Commodo ea ad commodo labore.\r\n",
       "registered": "2020-05-25T01:10:15 -10:00",
       "latitude": 60.769211,
       "longitude": -61.503084,
       "tags": [
         "nulla",
         "velit",
         "duis",
         "esse",
         "eiusmod",
         "elit",
         "ea"
       ],
       "friends": [
         {
           "id": 0,
           "name": "Elsa Camacho"
         },
         {
           "id": 1,
           "name": "Marla Morrison"
         },
         {
           "id": 2,
           "name": "Diane Boyer"
         }
       ],
       "greeting": "Hello, Durham Pace! You have 7 unread messages.",
       "favoriteFruit": "banana"
     }
   ]'
res:
  code: 201
