---
exec:
  mode: binary
  durationSeconds: 1
  threads: 128
  connections: 128
  logsampling: 0.1
  httpVersion: 2
req:
  method: GET
  url: https://localhost:8443/about
  headers:
    - Accept-Encoding: "identity"
res:
  code: 200
