---
exec:
  mode: binary
  durationSeconds: 30
  rampSeconds: 14
  concurrency: 128
  logsampling: 0.1
  httpVersion: 2
req:
  method: GET
  url: http://localhost:60083/mse6/get
  headers:
    - Accept-Encoding: "identity"
res:
  code: 200
