---
exec:
  durationSeconds: 30
  threads: 128
  connections: 128
req:
  method: POST
  url: http://localhost:60083/mse6/post
  headers:
    - Content-Type: "multipart/form-data"
  formData:
    - key1: value1
    - key2: value2
    - "@file1": ./p0d_80.png
    - "@file2": ./README.md
res:
  code: 200
