---
exec:
  mode: binary
  durationSeconds: 300
  dialTimeoutSeconds: 30
  rampSeconds: 60
  concurrency: 2048
  logsampling: 0.01
  httpVersion: 1.1
  skipInetTest: true
req:
  method: GET
  url: http://localhost:8080/mse6/get
  headers:
    - Accept-Encoding: "identity"
res:
  code: 200
