---
exec:
  durationSeconds: 30
  concurrency: 128
req:
  method: POST
  url: http://localhost:60083/mse6/post
  headers:
    - Content-Type: "application/x-www-form-urlencoded"
  formData:
    - key1: value1
    - key2: value2
res:
  code: 201
