---
exec:
  mode: binary
  durationSeconds: 300
  dialTimeoutSeconds: 30
  rampSeconds: 30
  concurrency: 128
  logsampling: 0.1
  httpVersion: 2
  skipInetTest: false
req:
  method: GET
  url: https://www.google.com/search?q=test
  headers:
    - Accept-Encoding: "identity"
res:
  code: 200
